"Disable vi compatible mode
" Need to be the first one
set nocompatible

" Sources
" https://vimawesome.com/
" https://blog.jez.io/vim-as-an-ide/
"
" --- Pluging manager: https://github.com/junegunn/vim-plug
" mkdir -p ~/.vim/autoload/
" fetch -o ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" wget -qP ~/.vim/autoload https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" curl https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
" --output ~/.vim/autoload/plug.vim"

call plug#begin()
" editorconfig
Plug 'editorconfig/editorconfig-vim'
" cool color
Plug 'altercation/vim-colors-solarized'
" Syntax check
Plug 'dense-analysis/ale'
" completion
Plug 'Shougo/deoplete.nvim'
" file manager
Plug 'preservim/nerdtree'
call plug#end()

" Plugin install (first time)
" :source %
" :PlugInstall

" --- General settings ---
" Automatically apply changes to the vimrc
if has("autocmd")
  autocmd! bufwritepost .vimrc source ~/.vimrc
endif
"Disable mouse
set mouse=

"Disable automatic tab when pasting
set noai
"Not enough, still doing it so enable past mode by default
set paste
"Enable syntax highlight
syntax enable
"Display line number
set number
"Display red line
set colorcolumn=80
"Enable incremental search
set incsearch
"Enable highlight in search mode
set hlsearch

" tap indent movement (use mark `m' for cursor position)
vmap <S-Tab>  mm<`m:<C-U>exec "normal ".&shiftwidth."h"<CR>mmgv`m
vmap <Tab>    mm>`m:<C-U>exec "normal ".&shiftwidth."l"<CR>mmgv`m

" --- Plugin settings ---
" -- Solarized
set background=light
"set background=dark
colorscheme solarized
" -- NERDtree
" Call it with F2
noremap <F2> :NERDTree<CR>
" --- Display
"TAB=4 space
"https://vim.fandom.com/wiki/Indenting_source_code
set shiftwidth=4
set tabstop=4

" Display insecable space (side effect of using bépo)
"highlight NbSp ctermbg=lightgray guibg=lightred
"match NbSp /\%xa0/
" Seems not working only for nbsp, use a different way:
set list listchars=tab:\ \ ,nbsp:␣
"highlight EdSp ctermbg=lightgray guibg=lightred
"match EdSp /\s\+$/
" Display unwanted space
highlight ExtraWhitespace ctermbg=red guibg=lightred
" Show trailing whitespace:
match ExtraWhitespace /\s\+$/
" Show trailing whitespace and spaces before a tab:
match ExtraWhitespace /\s\+$\| \+\ze\t/
" Show tabs that are not at the start of a line:
match ExtraWhitespace /[^\t]\zs\t\+/
" Show spaces used for indenting (so you use only tabs for indenting).
match ExtraWhitespace /^\t*\zs \+/
" Alternatively, the following pattern will match trailing whitespace, except when typing at the end of a line.
match ExtraWhitespace /\s\+\%#\@<!$/

" --- Input
" Do not use arrow!
"noremap <Up> <NOP>
"noremap <Down> <NOP>
"noremap <Left> <NOP>
"noremap <Right> <NOP>

"Load /usr/src/tools/tools/editing/freebsd.vim
"enable it with: \f
":so /usr/src/tools/tools/editing/freebsd.vim
"Enable to read the vim config file
set modeline

" --- Language

" ---- c
"Check common c errors
let c_space_errors=1

"autoindentation for python file

autocmd FileType html setlocal shiftwidth=2 tabstop=2
autocmd FileType python setlocal expandtab shiftwidth=4 softtabstop=4

"au BufNewFile,BufRead *.py
"    \ set tabstop=4
"    \ set softtabstop=4
"    \ set shiftwidth=4
"    \ set textwidth=79
"    \ set expandtab
"    \ set autoindent
"    \ set fileformat=unix
"   filetype indent off   " Disable file-type-specific indentation
"   syntax off            " Disable syntax highlighting

" --- BÉPO user remapping ---
source ~/.vimrc.bepo
