"Improve escape key delay
set timeoutlen=500 ttimeoutlen=0
"Load pathogen
execute pathogen#infect()
"filetype plugin indent on
"Disable vi compatible mode
"set nocompatible
"Enable syntax highlight
syntax enable
"Load solarized
set background=light
"set background=dark
"let g:solarized_termcolors=16
"let g:solarized_termcolors=256
colorscheme solarized
"TAB=4 space
set tabstop=4
"set shiftwidth=4
"set sw=4 noet
" display the cursoline
" set cursorline
" Display insecable space
highlight NbSp ctermbg=lightgray guibg=lightred
"autocmd ColorScheme * highlight NbSp ctermbg=lightgray guibg=lightred
match NbSp /\%xa0/
"highlight EdSp ctermbg=lightgray guibg=lightred
"match EdSp /\s\+$/
" Display unwanted space
highlight ExtraWhitespace ctermbg=red guibg=lightred
" Show trailing whitespace:
match ExtraWhitespace /\s\+$/
" Show trailing whitespace and spaces before a tab:
match ExtraWhitespace /\s\+$\| \+\ze\t/
" Show tabs that are not at the start of a line:
match ExtraWhitespace /[^\t]\zs\t\+/
" Show spaces used for indenting (so you use only tabs for indenting).
match ExtraWhitespace /^\t*\zs \+/
" Alternatively, the following pattern will match trailing whitespace, except when typing at the end of a line.
match ExtraWhitespace /\s\+\%#\@<!$/

"Check common c errors
"let c_space_errors=1

"Display red line
set colorcolumn=80
"Load /usr/src/tools/tools/editing/freebsd.vim
"enable it with: \f
":so /usr/src/tools/tools/editing/freebsd.vim
