PROG=   testrss
SRCS=   testrss.c
MAN=
#CFLAGS+= -I/usr/include
#OBJ= $(SRC:.c=.o)
#CFLAGS+= -I${.CURDIR}/../../../sys/dev/cxgbe -I${.CURDIR}/../../../sys -I.
BINDIR?= /usr/local/bin

.include <bsd.prog.mk>

